server:
  port: 7081

spring:
  messages:
    basename: i18n.bundle
    defaultencoding: "UTF-8"
  datasource:
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:tcp://localhost/~/test2
    initialization-mode: always
    driver-class-name: org.h2.Driver

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  hibernate:
    current_session_context_class: thread

  liquibase:
    change-log: classpath:liquibase/rootChangeLog.xml

logging:
  level:
    ROOT: info