DROP TABLE IF EXISTS TAUTHOR;
CREATE TABLE TAUTHOR(AUTHORID LONG AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS TGENRE;
CREATE TABLE TGENRE(GENREID LONG AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS TBOOK;
CREATE TABLE TBOOK(BOOKID LONG AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS TBOOKAUTHOR;
CREATE TABLE TBOOKAUTHOR(BOOKID LONG, AUTHORID LONG,
                          FOREIGN KEY(BOOKID) REFERENCES TBOOK(BOOKID) ON DELETE CASCADE,
                          FOREIGN KEY(AUTHORID) REFERENCES TAUTHOR(AUTHORID) ON DELETE CASCADE
                       );

DROP TABLE IF EXISTS TBOOKGENRE;
CREATE TABLE TBOOKGENRE(BOOKID LONG, GENREID LONG,
                          FOREIGN KEY(BOOKID) REFERENCES TBOOK(BOOKID) ON DELETE CASCADE,
                          FOREIGN KEY(GENREID) REFERENCES TGENRE(GENREID) ON DELETE CASCADE
                       );