application:
  locale: ru_RU

spring:
  messages:
    basename: i18n.bundle
    defaultencoding: "UTF-8"
  datasource:
    url: jdbc:h2:mem:testdb
    #jdbc:h2:tcp://localhost/~/test
    initialization-mode: always
    driver-class-name: org.h2.Driver
    schema: schema.sql
    data: data.sql

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  hibernate:
    current_session_context_class: thread

logging:
  level:
    ROOT: INFO