application:
  fileName: "testdata"
  locale: en_US
  numberCorrectAnswers: 4

messagesource:
  basename: "/i18n/bundle"
  defaultEncoding: "UTF-8"

spring:
  messages:
    basename: "/i18n/bundle"
    defaultencoding: "UTF-8"